version: '3'

networks:

  default:

services:
  email_challenge:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    container_name: lara_git
    networks:
      - default
    ports:
      - '8000:80'
    restart: unless-stopped
    volumes:
      - ../src/:/var/www/html/
  mariadb:
    image: mariadb
    restart: always
    container_name: maria_db
    environment:
      MARIADB_DATABASE: challenge
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb: